pipeline{
    agent any
   environment{
    AWS_ACCESS_KEY=credentials('access-key')
    AWS_SECRET_KEY=credentials('secret-key')
   }
    stages{
        
    
    stage('init'){
   steps {
    dir('Terraform')
    {
    sh 'terraform init -input=false'

    }
  }
    }
   


stage('Terraform Plan') {
  steps {
    dir('Terraform')
    {
    sh 'terraform plan -out=tfplan'

    }
  }
}

stage('Approval') {
  steps {
    input message: 'Review plan. Proceed to apply?'
  }
}

stage('Terraform Apply') {
  steps {
    dir('Terraform')
    {
    sh 'terraform apply tfplan'

    }
  }
}
    }
}